import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp, updateDoc } from 'firebase/firestore'
import { db } from '@/lib/firebase'

export type AdminProduct = { id: string; name: string; category: string; price: number; stock: number; status: 'Activo' | 'Agotado'; imageUrl?: string }
export type AdminOrder = { id: string; customer: string; email: string; items: number; total: number; status: 'Pendiente' | 'En preparación' | 'Enviado' | 'Entregado'; date: string }
export type AdminCustomer = { id: string; name: string; email: string; orders: number; spent: number; joined: string }

const mapProduct = (snapshot: any): AdminProduct => { const data = snapshot.data(); return { id: snapshot.id, name: String(data.nombre ?? data.name ?? ''), category: String(data.categoria ?? data.category ?? 'Remeras'), price: Number(data.precio ?? data.price ?? 0), stock: Number(data.stock ?? 0), status: Number(data.stock ?? 0) > 0 ? 'Activo' : 'Agotado', imageUrl: data.imagenUrl ?? data.imageUrl } }
export async function getAdminData() { const [productsSnapshot, ordersSnapshot, usersSnapshot] = await Promise.all([getDocs(collection(db, 'productos')), getDocs(query(collection(db, 'pedidos'), orderBy('fecha', 'desc'))), getDocs(collection(db, 'usuarios'))]); const products = productsSnapshot.docs.map(mapProduct); const orders = ordersSnapshot.docs.map((snapshot) => { const data = snapshot.data(); return { id: snapshot.id, customer: String(data.clienteNombre ?? data.customer ?? 'Cliente'), email: String(data.email ?? ''), items: Number(data.items ?? data.productos?.length ?? 0), total: Number(data.total ?? 0), status: data.estado ?? 'Pendiente', date: data.fecha?.toDate?.().toLocaleDateString('es-AR') ?? 'Sin fecha' } as AdminOrder }); const customers = usersSnapshot.docs.map((snapshot) => { const data = snapshot.data(); return { id: snapshot.id, name: String(data.nombre ?? 'Cliente'), email: String(data.email ?? ''), orders: Number(data.pedidos ?? 0), spent: Number(data.totalGastado ?? 0), joined: data.fechaRegistro?.toDate?.().toLocaleDateString('es-AR', { month: 'short', year: 'numeric' }) ?? 'Sin fecha' } }); return { products, orders, customers } }
export async function createProduct(input: Omit<AdminProduct, 'id' | 'status'>) { return addDoc(collection(db, 'productos'), { nombre: input.name, categoria: input.category, precio: input.price, stock: input.stock, imagenUrl: input.imageUrl ?? '', fechaCreacion: serverTimestamp() }) }
export async function updateProduct(id: string, input: Partial<Omit<AdminProduct, 'id' | 'status'>>) { return updateDoc(doc(db, 'productos', id), { ...(input.name !== undefined && { nombre: input.name }), ...(input.category !== undefined && { categoria: input.category }), ...(input.price !== undefined && { precio: input.price }), ...(input.stock !== undefined && { stock: input.stock }), ...(input.imageUrl !== undefined && { imagenUrl: input.imageUrl }), fechaActualizacion: serverTimestamp() }) }
export async function deleteProduct(id: string) { return deleteDoc(doc(db, 'productos', id)) }
export const canAccessAdmin = (role?: string) => role === 'admin'
export const formatARS = (value: number) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(value)
